//Регистрация нового пользователя
POST http://localhost:3000/signup
Content-Type: application/json

{
  "email": "testingsigninl@mail.ru",
  "password": "asadasfaaf",
  "name": "Жdas"
  }
####
//Аутентификация пользователя
POST http://localhost:3000/signin
Content-Type: application/json

{
  "email": "testingsignin@mail.com",
  "password": "additionalpassword"
}
###

// Достать всех пользователей
GET http://localhost:3000/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjQ0MWZmODcxOTIxZTRjYzI5N2I0YzciLCJpYXQiOjE2NDg3MjY2NjUsImV4cCI6MTY0OTMzMTQ2NX0.K0MugFqrAxBsX0D11IZTiEY5h4U3BzFlczyihlq2pKA


//Достать собственный профиль
###
GET http://localhost:3000/users/me
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjQ0MWZmODcxOTIxZTRjYzI5N2I0YzciLCJpYXQiOjE2NDg3MjY2NjUsImV4cCI6MTY0OTMzMTQ2NX0.K0MugFqrAxBsX0D11IZTiEY5h4U3BzFlczyihlq2pKA

//Достать конкретного пользователя
###
GET http://localhost:3000/users/62388ee6e8d3fe86d710d283
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjQ0MWZmODcxOTIxZTRjYzI5N2I0YzciLCJpYXQiOjE2NDg3MjY2NjUsImV4cCI6MTY0OTMzMTQ2NX0.K0MugFqrAxBsX0D11IZTiEY5h4U3BzFlczyihlq2pKA


//Обновить информацию о пользователе
###
PATCH http://localhost:3000/users/me
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjQ0MWZmODcxOTIxZTRjYzI5N2I0YzciLCJpYXQiOjE2NDg3MjY2NjUsImV4cCI6MTY0OTMzMTQ2NX0.K0MugFqrAxBsX0D11IZTiEY5h4U3BzFlczyihlq2pKA

{
  "name": "Alex",
  "about": "long story test updated twice"
}

//Обновить аватарку пользователя
###
PATCH http://localhost:3000/users/me/avatar
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjQ0MWZmODcxOTIxZTRjYzI5N2I0YzciLCJpYXQiOjE2NDg3MjY2NjUsImV4cCI6MTY0OTMzMTQ2NX0.K0MugFqrAxBsX0D11IZTiEY5h4U3BzFlczyihlq2pKA

{"avatar": "https://sdss.ru"}

//Достать все карточки
###
GET http://localhost:3000/cards
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjQ0MWZmODcxOTIxZTRjYzI5N2I0YzciLCJpYXQiOjE2NDg3MjY2NjUsImV4cCI6MTY0OTMzMTQ2NX0.K0MugFqrAxBsX0D11IZTiEY5h4U3BzFlczyihlq2pKA

//Добавить новую карточку
###
POST http://localhost:3000/cards
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjQ0MWZmODcxOTIxZTRjYzI5N2I0YzciLCJpYXQiOjE2NDg3MjY2NjUsImV4cCI6MTY0OTMzMTQ2NX0.K0MugFqrAxBsX0D11IZTiEY5h4U3BzFlczyihlq2pKA

{
  "name": "Onem",
  "link": "https://sdss.ru"
}

//Удалить конкретную карточку
###
DELETE http://localhost:3000/cards/62441ff871921e4cc297b4c7
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjQ0MWZmODcxOTIxZTRjYzI5N2I0YzciLCJpYXQiOjE2NDg3MjY2NjUsImV4cCI6MTY0OTMzMTQ2NX0.K0MugFqrAxBsX0D11IZTiEY5h4U3BzFlczyihlq2pKA

//Поставить лайк на карточку
###
PUT http://localhost:3000/cards/623982e56773aacc138acddf/likes
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjQ0MWZmODcxOTIxZTRjYzI5N2I0YzciLCJpYXQiOjE2NDg3MjY2NjUsImV4cCI6MTY0OTMzMTQ2NX0.K0MugFqrAxBsX0D11IZTiEY5h4U3BzFlczyihlq2pKA

//Убрать лайк с карточки
###
DELETE  http://localhost:3000/cards/623982e56773aacc138acddf/likes
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjQ0MWZmODcxOTIxZTRjYzI5N2I0YzciLCJpYXQiOjE2NDg3MjY2NjUsImV4cCI6MTY0OTMzMTQ2NX0.K0MugFqrAxBsX0D11IZTiEY5h4U3BzFlczyihlq2pKA

